### ISSUE TITLE
Feature Request:Improve documentation for LuaCoroutine

### ISSUE THREAD

**Issue by RadiantUwU** [WeaselGames/godot_luaAPI#108]
It's not clear whether the thread object that calls .resume() on the coroutine stops for it or not. What happens exactly when .resume() is called?

**Comment by Trey2k** [comment]
The resume methodnon LuaCoroutine is a blocking call. It will not return until either lua yields and is done executing.

**Comment by Trey2k** [comment]
If yield_await is called in a GDScript method that's exposed to lua. It will yield thd GDScript method. This is still experimental though.

**Comment by RadiantUwU** [comment]
> If yield_await is called in a GDScript method that's exposed to lua. It will yield thd GDScript method. This is still experimental though.

So basically it turns the running GDScript function into a coroutine?

**Comment by RadiantUwU** [comment]
The only thing that's needed is to update documentation saying its a blocking call.

**Comment by Trey2k** [comment]
> So basically it turns the running GDScript function into a coroutine?

Kind of yeah, its the same as using await anywhere else in GDSCript and having the lua coroutine yield. but when the corutine is resumed it will instead resume where await was called.



> The only thing that's needed is to update documentation saying its a blocking call. (for `resume()`)

And yeah that is probably a good idea. There is probably a lot of examples where documentation is not as clear as it should be. I always welcome help with it but I do plan on going through all off it again before the v2 stable release. Which I hope to make happen before godot 4.1 is stable.

**Comment by Trey2k** [comment]
Fixed in #125
