### ISSUE TITLE
Feature Request:can you add luasocket ?

### ISSUE THREAD

**Issue by boruis** [WeaselGames/godot_luaAPI#144]
can you add luasocket? i need this ,but don't know how to integrate.    https://github.com/lunarmodules/luasocket

**Comment by Trey2k** [comment]
Hello! So there is currently some issues regarding loading native C lua libraries with thus module. You can read about that here https://github.com/WeaselGames/godot_luaAPI/issues/100#issuecomment-1595558929

I am hoping you find a resolution for the issue in 2.1 hopefully. Until then though the only way to integrate with it would probably be to staticly compile it with the rest of luaAPI.

**Comment by boruis** [comment]
ok, thanks for your reply, i will try to staticly compile it with the luaAPI.

**Comment by Trey2k** [comment]
> ok, thanks for your reply, i will try to staticly compile it with the luaAPI.

Sounds good, feel free to join the [discord](https://discord.gg/vGazqdQZ7p) if you need help with it.

**Comment by Trey2k** [comment]
Support for this should of been added with #178. If any issues arise feel free to reopen.
