### ISSUE TITLE
Not working on the latest version Godot_v4.1-stable_win64.

### ISSUE THREAD

**Issue by lulersoft** [WeaselGames/godot_luaAPI#146]
Not working on the latest version Godot_v4.1-stable_win64.

**Comment by Trey2k** [comment]
Hello! I am sorry to hear you are having issues. Can you verify you are using the the v2.1-beta release of luaAPI? v2.0 is only compatible with 4.0 

You can find the latest version for the 2.1 beta [here](https://github.com/WeaselGames/godot_luaAPI/releases/tag/v2.1-beta2).
