### ISSUE TITLE
Show LUA files in FileSystem view

### ISSUE THREAD

**Issue by nornaro** [WeaselGames/godot_luaAPI#158]
Hi
It would be a nice thing, if it could add .lua to the files shown in FileSystem window.

**Comment by nornaro** [comment]
Wanted to add "feature request"  tag, but seems like I can't after it has been created

**Comment by Trey2k** [comment]
Sorry for not commenting on this, I think if I where to support this i would want it to come with editor support to. The most likely route for that to happen will be with https://github.com/WeaselGames/godot_luaCodeEdit which is still very WIP but in theory after the language server bindings are complete that can be tied into godot. We will see where that goes.

Im also not 100% certain on the process of creating custom resource types so there may be some unknown issues there.
