### ISSUE TITLE
Please add luajit ffi

### ISSUE THREAD

**Issue by baidwwy** [WeaselGames/godot_luaAPI#159]
Please add luajit ffi

**Comment by Trey2k** [comment]
Can you explain a little about what it is and how it would be helpful? I know thats their foreign function interface for accessing C methods. But I am not seeing a real advantage myself of using that over exposing methods how we currently do.

**Comment by baidwwy** [comment]
My game is translated from love2d
I used a lot of ffi and many Windows API
I know this will damage the sandbox environment, so this is just a suggestion

My English is very poor. Sorry, this is from Google Translate

**Comment by Trey2k** [comment]
> My game is translated from love2d I used a lot of ffi and many Windows API I know this will damage the sandbox environment, so this is just a suggestion

Looking into it, it seems ffi is only a library. Support should be possible. And the sandbox should be fine as it would not be the only library that can break the sandbox. Just like OS, just need to be careful using it.

**Comment by Trey2k** [comment]
You can now give Lua access to the ffi library via `lua.bind_libraries["ffi"]` using the latest release https://github.com/WeaselGames/godot_luaAPI/releases/tag/v2.1-beta6
