### ISSUE TITLE
v2.1-beta6 Releases gdextension-LuaJIT.zip Not Luajit

### ISSUE THREAD

**Issue by baidwwy** [WeaselGames/godot_luaAPI#163]
`
    var err: LuaError = lua.do_string("""
    print(_VERSION)
    """)
`

windows x86_64

**Comment by Trey2k** [comment]
This is correct, turns out the actions have a typo, should be `luaapi_luaver=jit`
https://github.com/WeaselGames/godot_luaAPI/blob/36ae02b761aa13df543387b77116b116e7980acb/.github/workflows/gdextension.yml#L422

I should have a fix shortly, stay posted

**Comment by Trey2k** [comment]
Okay luaJIT GDExtension build has been updated https://github.com/WeaselGames/godot_luaAPI/releases/tag/v2.1-beta6

**Comment by Trey2k** [comment]
Closing this for now, if you still have issues let me know!
