### ISSUE TITLE
Web export missing from Godot Asset Library downloads

### ISSUE THREAD

**Issue by IntangibleMatter** [WeaselGames/godot_luaAPI#174]
There is currently no web version of the gdextension in the version downloaded from the Godot asset library. Several months ago there was a commit that said it added Web support, but I cannot find web builds of the project anywhere.

**Comment by Trey2k** [comment]
Currently we need not build for web with GDExtension. Looks like its possible now, when that first was added it was still being worked on. Currently web builds are supported when using the editor and export templates provided on the releases page of this repo. 

Support for web GDExtension will probably come soon.
