### ISSUE TITLE
Android GDExtension builds failing

### ISSUE THREAD

**Issue by Trey2k** [WeaselGames/godot_luaAPI#187]
For some reason after updating godot-cpp to the 4.2 branch the android builds are failing. I am unsure if this is due to github runners or godot-cpp its self as of yet. For the time being the have been disabled as I dont have a lot of time to dig into the issue.

The error is it fails to find the ndk clang bin.

**Comment by Yanxiyimengya** [comment]
Hopefully, this issue will be resolved soon

**Comment by Trey2k** [comment]
> Hopefully, this issue will be resolved soon

I would love to see this resolved too. I feel like it has to be something simple. But github actions take so long to debug and iterate on I haven't spent the time on it yet.

**Comment by Connor-McCloskey** [comment]
Hey all! Has there been any more word on this? I was just looking at the export templates for Android and saw this 😅
