### ISSUE TITLE
Bug Report: Numbers returned from lua are always cast as floats

### ISSUE THREAD

**Issue by jbromberg** [WeaselGames/godot_luaAPI#209]
**Describe the bug**
When pushing an integer value to lua, it is always pulled back as a float.

**To Reproduce**
```gdscript
var lua := LuaAPI.new()
var num: int = 10
lua.push_variant("num", num)
var pulled = lua.pull_variant("num")
print(typeof(pulled)) # float
```

**Expected behavior**
The value should be of variant type integer.

**Comment by Supchik22** [comment]
Lua does not have Integer, it only has number which is similar to float https://www.lua.org/pil/2.3.html

**Comment by jbromberg** [comment]
Godot supports integers though. This is what I'm currently doing in my project but it's a bit hacky:
```gdscript
if value is float and fmod(value, 1) == 0:
    value = int(value)
```
