### ISSUE TITLE
Feature Request: Implement `threading` library.

### ISSUE THREAD

**Issue by RadiantUwU** [WeaselGames/godot_luaAPI#216]
**Is your feature request related to a problem? Please describe.**
Sometimes, one thread isn't enough, and you'd require more than one thread inside Lua. There is a huge limitation around how Lua's states are **not** thread-safe.

**Describe the solution you'd like**
I would like a `threading` library that allows the following:
- Creating new threads, them creating their own `LuaAPI` state.
- Creating shared tables
- Creating synchronization primitives, such as semaphores, condition variables, and mutexes.
- Creating `ContextedLuaFunction`s, queues or blocks the `LuaAPI` calling this function to run a function on the thread that created this.
  - This allows using upvalues by reference since it remains under the same `LuaAPI` state.
- Passing values between threads, this includes mostly tables, Godot objects, Lua functions (cloning via `lua_dump` and `lua_load`, fails if upvalues are unable to be passed by value), C functions, `ContextedLuaFunction`s, synchronization primitives, etc.
**Describe alternatives you've considered**
Using multiple `LuaAPI` states and using `RefCounted`s for multi-threading.

**Additional context**
I can open a pull request for this feature request if need be.

**Comment by KevBruner** [comment]
Lua is not thread safe, and cannot be made thread safe in a reasonable way. Suggest closing this request.

**Comment by RadiantUwU** [comment]
> Lua is not thread safe, and cannot be made thread safe in a reasonable way. Suggest closing this request.

Did you not read my... feature request...?
