### ISSUE TITLE
V1.1-stable release only has Linux builds

### ISSUE THREAD

**Issue by Trey2k** [WeaselGames/godot_luaAPI#51]
For some reason the v1.1-stavle release only has a limit build. We want editor, export templates and debug export templates for windows, Mac, Linux and web.

**Comment by OoIks** [comment]
I did compile Godot 3.5 for v1.1 stable:
https://www.mediafire.com/file/v8bjnzv74ccf7q7/godot.windows.tools.64.zip/file

**Comment by Trey2k** [comment]
> I did compile Godot 3.5 for v1.1 stable: https://www.mediafire.com/file/v8bjnzv74ccf7q7/godot.windows.tools.64.zip/file

Appreciate the assistance. I will plan on making the rest of the Godot builds here shortly for v1.1

**Comment by Trey2k** [comment]
There are now builds for windows, linux, and javascript. Still need to make macos builds.

**Comment by Trey2k** [comment]
This is completed
