### ISSUE TITLE
Feature Request: Pass reference of Lua class for metamethod overrides.

### ISSUE THREAD

**Issue by martimmatias** [WeaselGames/godot_luaAPI#63]
**Is your feature request related to a problem? Please describe.**  

It is currently not possible to know which LuaAPI or LuaThread instance has called a function or invoked a metamethod on custom userdata. 
There are two use cases that I can think of:

- Controlling access to variables, functions and objects with permissions or per mod, for example;
- Custom debug tools (custom logs);

**Describe the solution you'd like**  

I would like to have a reference LuaThread that invoked a metamethod passed as an argument for the respective metamethod handler. I would also like the option to have it passed as an argument to normal functions that are passed as global variants. Ideally, this would be optional and would require an extra argument (like a bool or enum, for example) when pushing a function into Lua.

**Describe alternatives you've considered**  

The best alternative right now is to not share objects between LuaThreads but create either proxy objects or new separate objects and push those into the thread's state.

**Additional context**  

No additional context.

**Comment by Trey2k** [comment]
I think this would be the correct approach. As far as metamethod overrides go, we need to decide if it is the first or last argument.
And for other functions. Would we want to add a third argument to push_variant (We cannot overload the method from cpp to GD) or do we want to add a new method and if so, what would its name be?

**Comment by martimmatias** [comment]
> As far as metamethod overrides go, we need to decide if it is the first or last argument. And for other functions. 

I think the Lua instance should be the first argument. See why I want Tuples to always be the last argument in this [issue](https://github.com/WeaselGames/godot_luaAPI/issues/64#issuecomment-1397680238).
Also, I believe some metamethods such as __call can accept any amount of arguments, which only strengthens my case.

> Would we want to add a third argument to push_variant (We cannot overload the method from cpp to GD) or do we want to add a new method and if so, what would its name be?

Like I mentioned in the other issue, I believe there should be a new function called "push_function" which accepts the following args: function_name, function_callback, n_args, unlimited_args: bool; and now: pass_lua_reference: bool. Ideally, the last 3 arguments would be optional having values by default.

**Comment by Trey2k** [comment]
That all sounds good to me. Seems very well thought out.

**Comment by Trey2k** [comment]
Reopening this as I had forgotten meta values are a thing. I think we can do away with this wrapper and store the extra info via meta values.

**Comment by Trey2k** [comment]
NVM, meta data only works on Objects. Callable is a base type.
