### ISSUE TITLE
Look into tuples as a type. 

### ISSUE THREAD

**Issue by Trey2k** [WeaselGames/godot_luaAPI#64]
This could be useful for Lua functions that have more than one returned value.

**Comment by Trey2k** [comment]
Another advantage is allowing GDFunctions to return multiple values to Lua as well. I think the way we will implment this is like a stack.
```gdscript
var tuple = LuaTuple.new()
tuple.push_back(var)
var = yuople.pop()
```

**Comment by Trey2k** [comment]
An interesting part of this is most of the cpp functions we have returning stuff to Lua return 1. After calling pushVariant on whatever Variant it has. We will need to check if it is a tuple before returning so we can adjust accordingly.

**Comment by martimmatias** [comment]
In this context, tuples are sequences of any amount of values that can be returned by or passed to Lua functions.

### Here are some examples of how tuples are used in Lua:
```lua
--Multiple return values
function myFunction()
    return 1, 2, 3
end

local x, y, z = myFunction()
```
```lua
--Any number of arguments
function sumAll(...)
    local args = {...}
    local returnValue = 0
    for index, number in pairs(args) do
        returnValue = returnValue + number
    end
    return returnValue
end

local value = sumAll(1,2,3,4,5,6,7,8,9,10)
```
```lua
--FYI, you can convert tables to tuples and back
local fruitA, fruitB, fruitC = table.unpack({"apple", "banana", "coconut"})

local fruits = table.pack(fruitA, fruitB, fruitC)
```
### GDScript, on the other hand, only supports one return value and a set amount of arguments. 
Because of this, we need a way to let the module know how many arguments our function expects and a way to return multiple values. 

- Additional arguments should be converted to one single argument of either a "Tuple" type or an array. 
- GDScript functions should return a "Tuple" type to let the module know that its returning multiple arguments and not an array/Lua table. 
- However, we don't want all functions that are exposed to Lua to have a Tuple argument.

### Here is how this could be accomplished:
```gdscript
func my_function(arg1: string, args: Tuple):
    var concat_string = arg1
    for arg in args.items():
        if arg is String:
            concat_string += arg
    return concat_string


var lua = LuaAPI.new()
# luaFunctionName, functionCallback, numberOfArgs, multipleArgs
lua.push_function("luaFunctionName", my_function, 1, true)
```
You wouldn't need to pass the number of args if there is a way to know (from C++) how many arguments a gdscript function expects.

```gdscript
func get_coordinates():
    return Tuple.from_array([10, 54, 37])


var lua = LuaAPI.new()
# luaFunctionName, functionCallback, numberOfArgs, multipleArgs
lua.push_function("GetCoordinates", get_coordinates, 0, false)
```
The previous code snippet shows how one could return multiple values. `numberOfArgs` and `multipleArgs` could be set to 0 and false, respectively, by default: 
```gdscript
lua.push_function("GetCoordinates", get_coordinates)
```

**Comment by Trey2k** [comment]
> In this context, tuples are sequences of any amount of values that can be returned by or passed to Lua functions.
> ### Here are some examples of how tuples are used in Lua:
> 
> ```lua
> --Multiple return values
> function myFunction()
>     return 1, 2, 3
> end
> 
> local x, y, z = myFunction()
> ```
> 
> ```lua
> --Any number of arguments
> function sumAll(...)
>     local args = {...}
>     local returnValue = 0
>     for index, number in pairs(args) do
>         returnValue = returnValue + number
>     end
>     return returnValue
> end
> 
> local value = sumAll(1,2,3,4,5,6,7,8,9,10)
> ```
> 
> ```lua
> --FYI, you can convert tables to tuples and back
> local fruitA, fruitB, fruitC = table.unpack({"apple", "banana", "coconut"})
> 
> local fruits = table.pack(fruitA, fruitB, fruitC)
> ```
> 
> ### GDScript, on the other hand, only supports one return value and a set amount of arguments.
> 
> Because of this, we need a way to let the module know how many arguments our function expects and a way to return multiple values.
> 
>     * Additional arguments should be converted to one single argument of either a "Tuple" type or an array.
> 
>     * GDScript functions should return a "Tuple" type to let the module know that its returning multiple arguments and not an array/Lua table.
> 
>     * However, we don't want all functions that are exposed to Lua to have a Tuple argument.
> 
> 
> ### Here is how this could be accomplished:
> 
> ```gdscript
> func my_function(arg1: string, args: Tuple):
>     var concat_string = arg1
>     for arg in args.items():
>         if arg is String:
>             concat_string += arg
>     return concat_string
> 
> 
> var lua = LuaAPI.new()
> # luaFunctionName, functionCallback, numberOfArgs, multipleArgs
> lua.push_function("luaFunctionName", my_function, 1, true)
> ```
> 
> You wouldn't need to pass the number of args if there is a way to know (from C++) how many arguments a gdscript function expects.
> 
> ```gdscript
> func get_coordinates():
>     return Tuple.from_array([10, 54, 37])
> 
> 
> var lua = LuaAPI.new()
> # luaFunctionName, functionCallback, numberOfArgs, multipleArgs
> lua.push_function("GetCoordinates", get_coordinates, 0, false)
> ```
> 
> The previous code snippet shows how one could return multiple values. `numberOfArgs` and `multipleArgs` could be set to 0 and false, respectively, by default:
> 
> ```gdscript
> lua.push_function("GetCoordinates", get_coordinates)
> ```

I ended up going with a wrapper class to hold the extra info rather then another method. See #71
