### ISSUE TITLE
Why does this not display the captured bug?

### ISSUE THREAD

**Issue by OoIks** [WeaselGames/godot_luaAPI#86]
```py
onready var OutputText = get_node("PlayUI/Output/Outputdit/output").text
onready var lua = Lua.new()
func luaCallBack(err):
	print(err)
	OutputText += err + "\n"
```

Why does it not display the error but instead prints it?

**Comment by OoIks** [comment]
Just saw. Was doing it wrong.

**Comment by OoIks** [comment]
Wait, is it possible to also display information from such as:
```lua
print("hi")
```

**Comment by Trey2k** [comment]
> Wait, is it possible to also display information from such as:
> 
> ```lua
> print("hi")
> ```

You can expose your own print function of the same name and it will override the default one.

**Comment by OoIks** [comment]
> > Wait, is it possible to also display information from such as:
> > ```lua
> > print("hi")
> > ```
> 
> You can expose your own print function of the same name and it will override the default one.

Damn thats amazing! Thanks for letting me know. Do you have discord? Where I could ask some more questions.
